### ISSUE TITLE
Support SPM

### ISSUE THREAD

**Issue by twodayslate** [Dashlane/SwiftDomainParser#5]

**Comment by Binlogo** [comment]
Sounds a reasonable request,  but SPM may not support include resources, since this library depend on a `.dat` file. 

Maybe it can't support SPM temporarily, until [[Accepted with Modifications] SE-0271: Package Manager Resources](https://forums.swift.org/t/accepted-with-modifications-se-0271-package-manager-resources/31021) complete. 😔

**Comment by twodayslate** [comment]
Yeah, can't wait for assets/resource support. Other libraries are including the contents inside the library (either directly or compressed string). Not a great solution but it does work. 

You can wrap the data with `#if SWIFT_PACKAGE` so other package support isn't bloated.

**Comment by twodayslate** [comment]
It has been added to the Swift Package Registry https://swiftpackageregistry.com/Dashlane/SwiftDomainParser

**Comment by adhumi** [comment]
@twodayslate Thank you!
